
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.host_name = "postgresql"
    config.vm.network "forwarded_port", guest: 5432, host: 15432, protocol: "tcp", host_ip: "127.0.0.1", auto_correct: true

    # config.vm.share_folder "bootstrap", "/mnt/bootstrap", ".", :create => true
    config.vm.provision "shell", path: "postgres_setup.sh"
end